name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: "Create Package"
      run: |
        echo "Creating ZIP File"
        zip -r ResellingTechClient.zip src/ composer.json README.md


    - name: Send NEW Versions Embed
      uses: SebastiaanZ/github-status-embed-for-discord@main
      with:
        # Discord webhook
        webhook_id: '951230248178024488' # Has to be provided as a string
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        repository: ${{ github.repository }}
        status: 'success'
        actor: ${{ github.actor }}
        sha: ${{ github.sha }}

      #- name: send new Versions File
      #  uses: appleboy/discord-action@master
      #  with:
      #    webhook_id: ${{ secrets.WEBHOOK_ID }} # Has to be provided as a string
      #    webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
      #    file: "./ResellingTechClient.zip"

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          *.zip
          

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
